-- require("fzf-lua").setup({
-- 	keymap = {
-- 		builtin = {
-- 			true,
--       ["<C-d>"]  = "preview-down",
--       ["<C-u>"]    = "preview-up",
-- 		},
-- 	},
-- })
--
require("fzf-lua").setup({"telescope"})
