#!/bin/bash
window_id=$(aerospace list-windows --all | awk -F'|' '$3 ~ /spotify_player/ {print $1; exit}')
curr_win=$(aerospace list-workspaces --focused)
curr_window_id=$(aerospace list-windows --workspace $curr_win | awk -F'|' '$3 ~ /spotify_player/ {print $1; exit}')

if [ -n "$curr_window_id" ]; then
		aerospace move-node-to-workspace --window-id $window_id S
elif [ -n "$window_id" ]; then
    focused_win=$(aerospace list-workspaces --focused)
    aerospace move-node-to-workspace --window-id $window_id $focused_win
    aerospace focus --window-id $window_id
else
	osascript -e '
				tell application "Ghostty"
						if not running then
								activate
								delay 0.5
						else
								activate
						end if
				end tell
				
				tell application "System Events"
						tell process "Ghostty"
								keystroke "n" using command down  -- New tab
								delay 0.2
								keystroke "exec spotify_player"
								keystroke return
						end tell
				end tell
				'
		aerospace layout floating --window-id $window_id
fi
