vim.keymap.set('n', '<leader>o', ':update<CR> :source<CR>', {silent = true})
vim.keymap.set('n', '<leader>w', ':write<CR>', {silent = true})
vim.keymap.set('n', '<leader>q', ':quit<CR>', {silent = true})
vim.keymap.set('n', '<leader>nh', ':nohl<CR>', {silent = true})
vim.keymap.set('n', 'H', ':bprev<CR>', {silent = true})
vim.keymap.set('n', 'L', ':bnext<CR>', {silent = true})
vim.keymap.set({ 'n', 'v', 'x' }, '<leader>y', '"+y<CR>', {silent = true})
vim.keymap.set({ 'n', 'v', 'x' }, '<leader>d', '"+d<CR>', {silent = true})


vim.keymap.set('n', '<leader> ', ":FzfLua files<CR>", {silent = true})
vim.keymap.set('n', '<leader>/', ":FzfLua grep_visual<CR>", {silent = true})
vim.keymap.set('n', '<leader>,', ":FzfLua buffers<CR>", {silent = true})
vim.keymap.set('n', '<leader>f', ":Pick files<CR>", {silent = true})
vim.keymap.set('n', '<leader>h', ":Pick help<CR>", {silent = true})
vim.keymap.set('n', '<leader>e', ":Oil --float<CR>", {silent = true})
vim.keymap.set('n', '<leader>lf', vim.lsp.buf.format, {silent = true})
vim.keymap.set('n', '<leader>gg', ":LazyGit<CR>", {silent = true})
vim.keymap.set('n', '<leader>gl', ":LazyGitLog<CR>", {silent = true})
vim.keymap.set('n', '<leader>nn', ":Noice<CR>", {silent = true})
vim.keymap.set('n', '<leader>nd', ":Noice dismiss<CR>", {silent = true})
